#!/usr/bin/env bash 
# Use ss command for wider compatibility
# Use -lpn options:
#  -l: display listening sockets
#  -p: show the process ID (PID) of the network connections
#  -n: do not resolve addresses (faster)
netstat -lp
